### ISSUE TITLE
Jittery, glitchy video/audio and desync on VP9 files with Opus audio codec

### ISSUE THREAD

**Issue by FrankEBailey** [JamesLinEngineer/RKMC#26]
My hardware is a MXQ Pro 4K running Marshmallow. I have several dozen music videos downloaded from YouTube with **VP9 video** codec and **Opus audio** codec. 1080p files in this format glitch terribly on the current RKMC release. Re-encoded to AVC/AAC with Handbrake they play perfectly though with slightly bigger file sizes. Lower-bitrate files in this same format mostly play fine. The question is whether it's a Rockchip limitation or a software issue. I can provide a few files for testing if necessary.

**Comment by mo123** [comment]
@FrankEBailey Hi, the MXQ Pro 4K is not a Rockchip device as far as I know, it is an Amlogic S905 device that uses completely different video playback capabilities and CPU. So RKMC will give no benefit for VP9 video playback for you. The Amlogic S905 chipset also doesn't support the VP9 codec, only the S905X CPU. So if you play low bitrate videos or 720p ones it might be using software decoding that work in that case but 1080p or 4K won't be decoded fast enough by software and need hardware acceleration.
For VP9 playback you need an Amlogic S905/S912 device or a Rockchip RK3229RK3328/RK3399 device to play it. You will also only be able to play VP9 properly in the built-in video player on Amlogic devices or use a Kodi 16.1 app with support for AMLCodec as Kodi 17.1 dropped support for the AMLCodec used for video decoding in Amlogic devices. Please make sure you indeed have a MXQ Pro 4K since there are so many of these devices with just a slightly different name but then they use a completely different chipset like MXQ 4K without the 'Pro' that is actually a RK3229 device that supports VP9 in RKMC but only runs Lollipop firmware. Hope it can help you a bit.

**Comment by FrankEBailey** [comment]
Hi, wow I started googling around and there are like dozens of different builds of this basic box, it's hard to know exactly what I have. I will get my serial no and see if I can find out. Thanks for the advice.

Just as an aside, the VP9 encoded clips that don't have audio encoded with the Opus codec all play fine. Opus seems to be the problem. Not that it's likely relevant to this thread.
